language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - "$HOME/.composer/cache/files"

matrix:
  include:
    - php: 5.6
      env:
        - dependencies=lowest
    - php: 7.0
      env:
        - DEPLOY_WEBSITE=true

before_script:
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
  - echo "Debug code:"
  - sed -i -re "s/dev-master/`git rev-parse --short HEAD`/" src/Application/config.php
  - cat src/Application/config.php
  - ls -la src/Application/config.*

script:
  - vendor/bin/phpunit

after_success:
  - if [ "$DEPLOY_WEBSITE" = "true" ]; then ./travis-prepare-release.sh && bin/couscous travis-auto-deploy; fi;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: duX9ViWZ8Iin85auMS4XM4r+FqzShZ0at4sylE3QnUdXe6X5jfxBdOO+L1mhY1JyJ/BA8TjUziGDZ2e8UvwkMHIZRe+eZIifqwm/8Y9P2lMFmVNoHC4qfESl4NgHShc4gFjeUYkhMRQLgHScY+lkY+N4HVz10Y1P6B3c4EBXSxg=
  file: bin/couscous.phar
  on:
    repo: CouscousPHP/Couscous
    tags: true
    php: '7.0'

