language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  global:
  - GIT_NAME: "'Couscous auto deploy'"
  - GIT_EMAIL: couscous@couscous.io
  - GH_REF: github.com/CouscousPHP/Couscous
  - secure: ePuwi73FIpzkIuk0XkbxiYb5M+HzTIKJy/tXBa5gWhSWq6FlI1fysDGvDcExnKyNH0z9sud0sNPBbi5O5z/rjqupoxoBLuFHfLG3NnLrvjQ2SAmrsIBWtsU737Vo5klbfJp3oJ0hrQCIlczwkfK5j+HbQmGUoS5w81pr3kPxfnc=
before_script:
  - composer install --no-progress
  - npm install -g bower
  - npm install -g less
  - npm install -g less-plugin-clean-css
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
script:
  - phpunit
after_success:
  - bin/couscous travis-auto-deploy
