name: Website

on:
    # This job runs when a new release is published
    release:
        types: [ published ]

jobs:

    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
            -   run: 'npm install -g less less-plugin-clean-css'
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none
                    ini-values: phar.readonly=Off
            -   uses: ramsey/composer-install@v1
            -   run: |
                    ./travis-prepare-release.sh
                    bin/couscous travis-auto-deploy
            -   name: Upload phar to release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    file: bin/couscous.phar
                    tag: ${{ github.ref }}
